### ISSUE TITLE
Examples or documentation for Selenium.Contrib.Pages.Modal and Selenium.Contrib.Pages.PartialPage

### ISSUE THREAD

**Issue by tmueller** [vtherry/selenium-navigation#1]
Hi,

I just started using this small library and quite like it. Since I am not a native C# programmer, I am not able to infer how to use Selenium.Contrib.Pages.Modal and Selenium.Contrib.Pages.PartialPage just from reading the source. 

Could you be so kind to provide an example or documentation for Selenium.Contrib.Pages.Modal and Selenium.Contrib.Pages.PartialPage. That would be great.

**Comment by vtherry** [comment]
Hi Thomas,

sorry for the late response.
The idea behind Selenium.Contrib.Pages.Modal and Selenium.Contrib.Pages.PartialPage is quite simple.

First, the partial page is used to describe a part of a page. 
It acts like a user control or a component.
We can use a partial page for reusability of code that could be present in many pages like a header, a footer, a menu, a fieldset in a form,  etc...
Then we can enter the component, act on it, and if we don't navigate to another page, return to the caller page or component (you can nest components as you want by composing your page).

The modal is a specialization of a PartialPage. It is used to describe a modal window (pop-up) that has a title. You could specialize more to your need by inheriting from modal and creating your own ModalConfirm (adding Yes/No button), an ModalInfo (Ok button), etc ...

I had designed the Modal with a title to suit my little needs but you can enhance it to your need or design other components to reflects the components you have in you web app.

I can provide you with a little pet project that has some pages, partials and modals to understand how it works altogether.

Regards,

Vincent
